name: "slack-bot-action"
description: "Sends custom message to person or channel of your choice"

inputs:
  destination:
    description: "Channel or user that will receive message."
    required: true
  message:
    description: "Message that will be sent."
    required: true
    default: "testing"
  slack-token:
    description: "Slack Token, can be stored as a secret in the repo."
    required: false
  results:
    description: "List of job results to append to the message. New line separated with:  job:result"
    required: false
  github-token:
    description: "GitHub Repository to for getting commit email. Use: secrets.GITHUB_TOKEN "
    required: false
  github-repository:
    description: "GitHub Repository to for getting commit email. Default: github.repository"
    required: false
  github-sha:
    description: "GitHub SHA to for getting commit email. Default: github.sha"
    required: false
  remove-branch-prefix:
    description: "Removes branch /refs/head/ from string instances of /refs/heads. Values: true/false"
    required: false
    default: "true"
  fallback-destination:
    description: "Destination to use if any of the destinations fail."
    required: false
    default: '#alerts-unknown-team'
outputs:
  validate-output:
    description: "Status of message"
    value: ${{ steps.run-slackbot.outputs.validate-output }}
runs:
  using: composite
  steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find Slack user
        id: find-slack-user
        uses: scribd/find-slack-user-action@v1
        with:
          slack-token: ${{ inputs.slack-token }}

      - shell: bash
        id: parse_result
        env:
          INPUT_DESTINATION: ${{ inputs.destination }}
          INPUT_FALLBACK-DESTINATION: ${{ inputs.fallback-destination }}
          INPUT_GITHUB-REPOSITORY: ${{ github.repository }}
          INPUT_GITHUB-SHA: ${{ github.sha }}
          INPUT_GITHUB-TOKEN: ${{ github.token }}
          INPUT_MESSAGE: ${{ inputs.message }}
          INPUT_REMOVE-BRANCH-PREFIX: ${{ inputs.remove-branch-prefix }}
          INPUT_RESULTS: ${{ inputs.results }}
          INPUT_SLACK-TOKEN: ${{ inputs.slack-token }}
        run: |
          parsed_results=$(python ${{ github.action_path }}/parser.py "$INPUT_RESULTS")

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "text<<$EOF" >> $GITHUB_OUTPUT
          echo "$INPUT_MESSAGE" >> $GITHUB_OUTPUT
          echo "$parsed_results" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

          committerid="${{ steps.parse_result.outputs.member-id }}"

          if [[ "$INPUT_DESTINATION" == "#"* ]]; then
            echo "destination=$INPUT_DESTINATION" >> $GITHUB_OUTPUT
            echo "1"
          elif [[ "$INPUT_DESTINATION" == "committer" && "${{ github.event.pusher.email }}" == *"@patriotsoftware.com" ]]; then
            echo "destination=$committerid" >> $GITHUB_OUTPUT
            echo "$committerid"
            echo "2"
          elif [[ "$INPUT_FALLBACK-DESTINATION" == "committer" && "${{ github.event.pusher.email }}" == *"@patriotsoftware.com" ]]; then  
            echo "destination=$committerid" >> $GITHUB_OUTPUT
            echo "3"
          elif [[ "$INPUT_FALLBACK-DESTINATION" == "#"* ]]; then
            echo "destination=$INPUT_FALLBACK-DESTINATION" >> $GITHUB_OUTPUT
            echo "4"
          fi

      - name: Print Slack user
        shell: bash
        run: |
          echo "Start"
          echo "${{ steps.parse_result.outputs.destination }}"
          echo "${{ steps.find-slack-user.outputs.member-id }}"
          echo "${{ steps.parse_result.outputs.text }}"
          echo "finish"
          
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.27.0        
        env:
          SLACK_BOT_TOKEN: ${{ inputs.slack-token }}
        with:
          channel-id: "${{ steps.parse_result.outputs.destination }}"
          slack-message: "${{ steps.parse_result.outputs.text }}"



