name: "slack-bot-action"
description: "Sends custom message to person or channel of your choice"

inputs:
  destination:
    description: "Channel or user that will receive message."
    required: true
  message:
    description: "Message that will be sent."
    required: true
    default: "testing"
  slack-token:
    description: "Slack Token, can be stored as a secret in the repo."
    required: false
  results:
    description: "List of job results to append to the message. New line separated with:  job:result"
    required: false
  github-token:
    description: "GitHub Repository to for getting commit email. Use: secrets.GITHUB_TOKEN "
    required: false
  username-mapping-repository:
    description: "GitHub Repository that contains the github -> slack username mapping file."
    required: false
    default: "SynergyDataSystems/GHA.Shared"
  username-mapping-path:
    description: "Path relative to the root of the repository that contains the github -> slack username mapping file."
    required: false
    default: ".github/username-mapping.yml"
  remove-branch-prefix:
    description: "Removes branch /refs/head/ from string instances of /refs/heads. Values: true/false"
    required: false
    default: "true"
  fallback-destination:
    description: "Destination to use if any of the destinations fail."
    required: false
    default: '#alerts-unknown-team'
outputs:
  validate-output:
    description: "Status of message"
    value: ${{ steps.run-slackbot.outputs.validate-output }}

runs:
  using: docker
  image: 'Dockerfile' # swap to released image once done testing
  env:
    GITHUB_INPUTS: ${{ toJSON(inputs) }}

# - name: Post to a Slack channel
#   id: slack
#   if: ${{ steps.parse_result.outputs.destination != 'disabled' }}
#   uses: slackapi/slack-github-action@v1.27
#   env:
#     SLACK_BOT_TOKEN: ${{ inputs.slack-token }}
#   with:
#     channel-id: "${{ steps.parse_result.outputs.destination }}"
#     slack-message: "${{ steps.parse_result.outputs.text }}"
