name: "slack-bot-action"
description: "Sends custom message to person or channel of your choice"

inputs:
  destination:
    description: "Channel or user that will receive message."
    required: true
  message:
    description: "Message that will be sent."
    required: true
    default: "testing"
  slack-token:
    description: "Slack Token, can be stored as a secret in the repo."
    required: false
  results:
    description: "List of job results to append to the message. New line separated with:  job:result"
    required: false
  github-token:
    description: "GitHub Repository to for getting commit email. Use: secrets.GITHUB_TOKEN "
    required: false
  github-repository:
    description: "GitHub Repository to for getting commit email. Default: github.repository"
    required: false
  github-sha:
    description: "GitHub SHA to for getting commit email. Default: github.sha"
    required: false
  remove-branch-prefix:
    description: "Removes branch /refs/head/ from string instances of /refs/heads. Values: true/false"
    required: false
    default: "true"
  fallback-destination:
    description: "Destination to use if any of the destinations fail."
    required: false
    default: '#alerts-unknown-team'
outputs:
  validate-output:
    description: "Status of message"
    value: ${{ steps.run-slackbot.outputs.validate-output }}
runs:
  using: composite
  steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - shell: bash
        id: parse_result
        env:
          INPUT_DESTINATION: ${{ inputs.destination }}
          INPUT_FALLBACK-DESTINATION: ${{ inputs.fallback-destination }}
          INPUT_GITHUB-REPOSITORY: ${{ github.repository }}
          INPUT_GITHUB-SHA: ${{ github.sha }}
          INPUT_GITHUB-TOKEN: ${{ github.token }}
          INPUT_MESSAGE: ${{ inputs.message }}
          INPUT_REMOVE-BRANCH-PREFIX: ${{ inputs.remove-branch-prefix }}
          INPUT_RESULTS: ${{ inputs.results }}
          INPUT_SLACK-TOKEN: ${{ inputs.slack-token }}
        run: |
          parsed_results=$(python parser.py "$INPUT_RESULTS")
          message=$(echo $parsed_results | tr '\n' ' ')
          echo "text=$message" >> $GITHUB_OUTPUT
      #     echo "results=$parsed_results" >> $GITHUB_OUTPUT

      #     if [[ "$INPUT_DESTINATION" == "#"* ]]; then
      #       echo "destination=$INPUT_DESTINATION" >> $GITHUB_OUTPUT
      #     elif [[ "$INPUT_DESTINATION" == "committer" && "${{ github.event.pusher.email }}" == *"@patriotsoftware.com" ]]; then
      #       echo "destination=${{ github.event.pusher.email }}" >> $GITHUB_OUTPUT
      #     elif [[ "$INPUT_FALLBACK-DESTINATION" == "committer" && "${{ github.event.pusher.email }}" == *"@patriotsoftware.com" ]]; then  
      #       echo "destination=${{ github.event.pusher.email }}" >> $GITHUB_OUTPUT
      #     elif [[ "$INPUT_FALLBACK-DESTINATION" == "#"* ]]; then
      #       echo "destination=$INPUT_FALLBACK-DESTINATION" >> $GITHUB_OUTPUT
      #     fi

      - shell: bash
        run: "${{ steps.parse_result.outputs.message }}"

      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.27.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      #     channel-id: ${{ steps.parse_result.outputs.destination }}
      #     # For posting a simple plain text message
      #     slack-message: "$INPUT_MESSAGE\n${{ steps.parse_result.outputs.results }}" #"GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ inputs.slack-token }}

 # - name: Download Slackbot release
    #   uses: robinraju/release-downloader@v1
    #   with:
    #     repository: patriotsoftware/slack-bot-action
    #     latest: true
    #     fileName: slackbot


