name: "slack-bot-action"
description: "Sends custom message to person or channel of your choice"

inputs:
  destination:
    description: "Channel or user that will receive message."
    required: true
  message:
    description: "Message that will be sent."
    required: true
    default: "testing"
  slack-token:
    description: "Slack Token, can be stored as a secret in the repo."
    required: false
  results:
    description: "List of job results to append to the message. New line separated with:  job:result"
    required: false
  github-token:
    description: "GitHub Repository to for getting commit email. Use: secrets.GITHUB_TOKEN "
    required: false
  github-repository:
    description: "GitHub Repository to for getting commit email. Use: github.repository"
    required: false
  github-sha:
    description: "GitHub SHA to for getting commit email. Use: github.sha"
    required: false

outputs:
  validate-output:
    description: "This is used to validate success of the action."
runs:
  using: node12
  main: slack-bot-action.js
  

    
