#!/usr/bin/env python3

import yaml
import sys

def load_user_mapping(file_path):
  with open(file_path, 'r') as file:
    return yaml.safe_load(file)

def lookup_user(user_mapping, key):
  return user_mapping.get(key, "Key not found")

if __name__ == "__main__":
  if len(sys.argv) != 3:
    print("Usage: python slack_id.py <mapping_file> <key>")
    sys.exit(1)

  mapping_file = sys.argv[1]
  key = sys.argv[2]

  user_mapping = load_user_mapping(mapping_file)
  value = lookup_user(user_mapping, key)

  print(value)
