name: Build & Release Slackbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-action:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - id: get-current-version
        run: |
              # major contains the 'v'
              echo "major=$(echo $(git describe --abbrev=0 --tags) | cut -d '.' -f 1)" >> $GITHUB_OUTPUT
              echo "minor=$(echo $(git describe --abbrev=0 --tags) | cut -d '.' -f 2)" >> $GITHUB_OUTPUT
              echo "patch=$(echo $(git describe --abbrev=0 --tags) | cut -d '.' -f 3)" >> $GITHUB_OUTPUT
              
      - id: update-minor-version
        run:
          updated-version=${{steps.get-current-version.outputs.minor}}+1
          echo "updated-minor-version=$updated-version" >> $GITHUB_OUTPUT
          
      - id: update-current-version
        run: |
            echo ${{steps.update-minor-version.outputs.updated-minor-version}}
            echo "New Version is ${{steps.get-current-version.outputs.major}}.${{steps.update-minor-version.outputs.updated-minor-version}}.${{steps.get-current-version.outputs.patch}}"
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            echo "Updating Minor Version"
            git tag -fa "${{steps.get-current-version.outputs.major}}.${{steps.update-minor-version.outputs.updated-minor-version}}.${{steps.get-current-version.outputs.patch}}" -m "Minor Version Update"
            git push --force origin "${{steps.get-current-version.outputs.major}}.${{steps.update-minor-version.outputs.updated-minor-version}}.${{steps.get-current-version.outputs.patch}}"            

            echo "Retagging Major Version
            git tag -fa "${{steps.get-current-version.outputs.major}}" -m "Major Version Retag"
            git push --force origin "${{steps.get-current-version.outputs.major}}"
