name: Release New Bot Version

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-action:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version
        id: bump-version
        uses: patriotsoftware/semver-bump-action@v1

      - name: Build Binary
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
      - run: go build -ldflags="-s -w" -o slack-bot

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ steps.bump-version.outputs.resulting-semver-tag }}
          files: slack-bot
