name: Build & Release Slackbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-action:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
   
      # - name: Minor version for each merge
      #   id: taggerDryRun
      #   uses: anothrNick/github-tag-action@1.36.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true
      #     DRY_RUN: true
  
      # - name: echo new tag
      #   run: |
      #     echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      # - name: echo tag
      #   run: |
      #     echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      # - name: echo part
      #   run: |
      #     echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"
    
      - name: Minor version for each merge
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
