name: Build & Release Slackbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-action:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Git Tag
        id: bump-version
        uses: patriotsoftware/semver-bump-action@v1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ steps.bump-version.outputs.resulting-semver-tag }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
