name: Build & Release Slackbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-action:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version
        id: bump-version
        uses: patriotsoftware/semver-bump-action@v1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Binary
        run: |
          go build \
            -ldflags "-s -w -extldflags '-static'" \
            -o slackbot \
            . \
            && strip slackbot \
            && upx -q -9 slackbot

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ steps.bump-version.outputs.resulting-semver-tag }}
          files: slackbot
