name: Deploy a New SlackBot

on: 
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:

jobs:
  build-test-slackbot:
    name: Test Slackbot
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Slackbot Channel Test
        id: trigger-slackbot-channeltest
        uses: ./
        with:
          destination: committer
          message: "A new slackbot update has been triggered."
          slack-token: ${{ secrets.SLACK_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fallback-destination: "#alerts-devops"

      # Print out the outputs from the previous step
      - name: Verify Output
        run: |
          if [ -z "${{ steps.trigger-slackbot-channeltest.outputs.validate-output }}" ]; then
            echo "❌ Step did not complete successfully."
            exit 1
          fi
          echo "✅ Action completed"
          echo "${{ steps.trigger-slackbot-channeltest.outputs.validate-output }}"
