name: Test Action

on:
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:

jobs:
  test-slackbot:
    name: Test slackbot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trigger Slackbot Channel Test
        id: trigger-slackbot-channel-test
        uses: patriotsoftware/slack-bot-action@use-official-action
        with:
          destination: committer
          message: "A new slackbot update has been triggered."
          slack-token: ${{ secrets.SLACK_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fallback-destination: "#alerts-devops"
          results: |
           "Project Validation:success
            ReSharper Inspections:failure
            Deploy Dev:neither"

      - name: Print Status
        run: echo output from slackbot '${{ steps.trigger-slackbot-channel-test.outputs.validate-output }}'
