name: Test Action

on:
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:

jobs:
  build-test-slackbot:
    name: Build Slackbot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: octokit/request-action@v2.x
        id: get_commit_email
        with:
          route: GET /repos/patriotsoftware/slack-bot-action/commits/${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Slackbot Channel Test
        id: trigger-slackbot-channeltest
        uses: patriotsoftware/slack-bot-action@v1
        with:
          destination: committer
          message: "A new slackbot update has been triggered."
          slack-token: ${{ secrets.SLACK_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fallback-destination: "#alerts-devops"
